Source/GA6thFinal_Framework/FileSystem/Core/FileObserver.cpp, Source/GA6thFinal_Framework/FileSystem/Core/FileObserver.h, Source/GA6thFinal_Framework/FileSystem/FileHelper.h
fix/filesystem-> develop
---
- FileObserver 스레드 종료 시 간헐적으로 무한 블로킹하는 현상 수정. (약 50회 정도 종료 테스트 완료)
- 스레드 종료 확인 디버그 로그 추가
---
---
- Git Issue: #
=> [FIX] FileObserver 스레드 종료 시 간헐적으로 무한 블로킹하는 현상 수정

Source/GA6thFinal_Framework/FileSystem/Core/FileSystem.cpp, Source/GA6thFinal_Framework/FileSystem/Core/FileSystem.h, Source/GA6thFinal_Framework/FileSystem/Extra/FileContext.cpp, Source/GA6thFinal_Framework/FileSystem/Extra/FileContext.h, Source/GA6thFinal_Framework/FileSystem/Extra/FileEventNotifier.cpp, Source/GA6thFinal_Framework/FileSystem/Extra/FileEventNotifier.h, Source/GA6thFinal_Framework/FileSystem/Extra/FileEventProcesser.h, Source/GA6thFinal_Framework/FileSystem/FileSystem.vcxproj, Source/GA6thFinal_Framework/FileSystem/FileSystem.vcxproj.filters, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
feature/filesystem_eventnotifire -> develop
---
- FileSystem EventNotifire 등록 방법 수정. (확장자 이니셜라이즈 리스트를 생성자 매개변수  -> Register 매개변수) 
- FileContext의 EventProcessor 사용 안함 이슈로 삭제
---
---
- Git Issue: #
=> [FEAT] filesystem EventNotifier 등록 방법 수정 및 파일 컨텍스트 EventProcessor 삭제

.github/workflows/create-jira-issue.yml
---
- 부모로 작성된 작업의 타입을 출력하는 부분 추가
---
.
---
- Git Issue: #
=> [CI/VG-135] 부모 작업 로그 찍기

Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileContext.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileContext.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileEventNotifier.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Interface/IFileEventProcesser.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileDataType.cpp
develop <- fix/VG-29/file_system
---
- 폴더가 메타 추적 못하는 현상 수정
- 네이밍 일부 수정
---
---
- Git Issue: #91
=> [fix/VG-29] 파일 시스템 폴더가 메타 추적 못하는 현상 수정

Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/ReflectHelper.h, Source/GA6thFinal_Framework/GameScripts/Scripts/Test/TestComponent.h
---
- ReflectFields에서 const 한정자 함수도 접근 가능하도록 오버라이딩 추가
- TestComponent로 빌드 확인 완료.
---
---
- Git Issue: #94
- Jira Ticket Number: VG-195
=> [FIX/VG-195] ReflectFields에서 const 한정자 함수도 접근 가능하도록 오버라이딩 추가

Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileEventNotifier.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
develop <- feature/VG-/file_system
---
- 유연한 대처를 위해 FileEventNotifier클래스에 파일 관련 이벤트 콜백 함수 추가
---
---
- Git Issue: #
=> [feture/VG-29] 파일 관련 이벤트 콜백 함수 추가

Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
---
- 파일 Removed 이벤트의 empty Guid반환 오류 수정
---
---
- Git Issue: #101
- Jira Ticket Number: VG-239
=> [fix/VG-239] 파일 Removed 이벤트의 empty Guid반환 오류 수정

Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Scene/EditorSceneMenu.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Log/EditorLogsTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Log/EditorLogsTool.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.h
develop <- feature/VG-28/scene_editor_prefab
---
- 로그 가독성 기능 강화
- 오브젝트 역직렬화 및 씬 역직렬화 GUID 사용하도록 수정
- 역직렬화된 Prefab 오브젝트들 GameObjectFactory가 추적하도록 수정
---
---
=> [FAETURE/VG-28] 오브젝트 및 씬 직렬화 기능 버그 수정 및 에디터에서 할 수 있도록 추가

Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GBufferPass.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.h, Source/GA6thFinal_Framework/GameScripts/Scripts/Graphics/MeshRenderer.h, Source/GA6thFinal_Framework/GameScripts/Scripts/Graphics/StaticMeshRenderer.cpp
develop <- fix/VG-261/bug_render_component_dangling_pointer
---
- 어떤 작업을 했는지 요약
- Scene 재 로드 시 렌더러 컴포넌트에서 터지던 버그 수정
- 
---
---
- Git Issue: #117 
- Jira Ticket Number: VG-261
=> [FIX/VG-261] Scene 재 로드 시 렌더러 컴포넌트에서 터지던 버그 수정

Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileDataType.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileDataType.h, Source/GA6thFinal_Framework/ProjectVG/ProjectSettings/SceneManager.setting.json
develop <- fix/VG-272/file_system_bug_fix
---
- Null Guid가 루트 경로를 반환하는 버그 수정.
- Load, Registered 이벤트 순서 변경 (Git Issue #122, Jira Ticket Number VG-273)
---
---
- Git Issue: #121 
- Jira Ticket Number: VG-272
=> [FIX/VG-272] Null Guid가 루트 경로를 반환하는 버그 수정.

Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
develop <- fix/VG-28/scene_file_write_fix
---
- scene 파일, prefab 파일 저장시 경로 이상한곳에 저장하는 문제들 수정
---
---
=> [FIX/VG-28] scene 파일, prefab 파일 저장시 경로 이상한곳에 저장하는 문제들 수정

Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj, Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters, Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/ImGuiDX12Module.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorGui.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Interface/IEditorObject.h, Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h, Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
develop <- feature/VG-28/build_setting_fix
---
- 에디터 모듈을 에디터 빌드가 아닌 곳에서 접근하면 에러나도록 수정.
- IEditorObject 파일 분리
---
---
=> [FEATURE/VG-28] Build setting fix

Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/DeferredPBRLitPass.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GBufferPass.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/PBRLitTechnique.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderTarget.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderTarget.h, Source/GA6thFinal_Framework/Shaders/ps_gbuffer.hlsl, Source/GA6thFinal_Framework/Shaders/ps_pbr_lighting.hlsl
---
- 배경에 lighting 연산 안들어감. 
---
---
- Git Issue: #
=> [FIX/VG-32] 배경에 lighting 연산 안들어가게 만듬.

Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Project/EditorProjectMenu.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/DockWindow/EditorDockWindow.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Tool/EditorTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.h
develop <- feature/VG-29/feature/VG-29/file_system
---
- 파일 열기 브라우저 기능 추가(폴더 열기, 파일 저장, 파일 열기(다중 선택 가능))
- 윈도우 닫기 버튼 누를 시 저장 메세지 박스를 취소했을 때 윈도우가 안 닫히도록 변경
---
---
- Git Issue: #
=> [FEATURE/VG-29] 파일 시스템 API 추가 및 윈도우 닫기 시 취소 누르면 안닫히도록 변경

Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
develop <- fix/VG-29/file_system
---
- 윈도우 닫기 버튼 누를 시 프로젝트 로드 안되어있을 때 무시되는 버그 수정
---
---
- Git Issue: #
=> [FIX/VG-29] 윈도우 닫기 프로젝트 로드 안했을 시 무시되는 버그 수정

Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
develop <- fix/VG-28/scene_editor_fix
---
- scene 에디터 포커스일때만 카메라 움직이게 수정
---
---
- Git Issue: #
- Jira Ticket Number: VG-28
=> [FIX/VG-28] scene 에디터 포커스일때만 카메라 움직이게 수정

Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.cpp
develop <- feature/VG-/32feature_dx12_graphics_core_devleop
---
- Scene Initialize 누락된 부분 추가
---
=> [FIX/VG-32] 씬 초기화 안되는 버그 수정

Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GBufferPass.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GBufferPass.h
---
- GBuffer에서 Shader의 배열에 잘못된 인덱스로 접근하는 버그 수정
---
=> [FIX/VG-32] GBuffer에서 Shader의 배열에 잘못된 인덱스로 접근하는 버그 수정

Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/FocusCommand.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.h, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/HierarchyFindTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Adapter/Controller/XInput/XInputAdapter.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Devices/Controller/Controller.h, Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/MeshComponent.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/MeshComponent.h, Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Input/InputTestComponent.cpp
develop <- refactor/VG-28/scene_input_refactor
---
- Play / Stop 전환할때 터지는 버그 수정
- 포커스 오브젝트 null 접근하는 버그 수정
- RayPicker로 선택된 오브젝트의 하이러키 TreeNode가 펼쳐지는 기능 추가
- 하이러키 오브젝트 선택시 외각선 표시하는 기능 버그 수정
- Scene Input System 리팩토링 
---
---
=> [REFACTOR/VG-28] scene input refactor

Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
develop <- fix/VG-28/scene_view_editor_sort_fix
---
- 씬 뷰어에서 클릭해서 오브젝트 선택할때 카메라 기준 가까운것 먼저 선택 안하는 버그 수정
---
---
=> [FIX/VG-28] Scene RayPicker에서 카메라 기준 정렬 안하는 버그 수정

Source/GA6thFinal_Framework/GameEngine/Source/Editor/DynamicCamera/EditorDynamicCamera.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/DynamicCamera/EditorDynamicCamera.h, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Command/EditorCommandTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Command/EditorCommandTool.h, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Debug/EditorDebugTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DetachChildrenCommand.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/FocusCommand.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.h, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.h
---
- Dynamic Camera
a. 이동 관련 Min-Max Speed 변수 추가.
b. 카메라가 동작 중인지 여부 반환 함수 추가
c. PivotPosition도 설정 가능하게 변경
d. Update함수 도중 필요 없는 변수 제거
e. MoveScale 변수 제거. MoveSpeed랑 혼용
- SceneTool
a. SetCameraFocusObject -> SetCameraToObject로 변경. (유연하게 쓰기 위해 인자를 받는 방식으로 변경)
b. CameraFocus 중 선형 보간을 하도록 변경
c. Manipulate에 마우스 델타가 존재하는 경우에만 커맨드를 실행하도록 변경
d. Manipulate가 호출중일 때만 관련 단축키가 동작하도록 변경
e. RayPicker 평가 값이 false일 시 Focus 리셋하는 기능 추가
- HierarchyTool
a. 더블 클릭 시 SceneView가 해당 객체를 SetCameraToObject하는 기능 추가
b. Transform의 Drag&Drop을 Frame에다 끌어놓을 경우 Root(부모가 없음)상태로 변경하는 기능 추가
- InspectorTool
a. FocusObject를 초기화하는 함수 추가 (outline 및 Manipulate 포함)
- FocusCommand
a. 이미 포커싱 중인 객체라면 넘기도록 변경
- CommandTool
a. 커맨드가 갱신될 때 스크롤을 내리도록 변경
b. 사이즈 관련 함수 및 변수 size_t 자료형으로 변경
- …
=> [FEATURE/VG-29] 에디터 버그 및 편의성 개선

Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
develop <- fix/VG-28/delay_scene_load
---
- 로드된 씬 오브젝트 추가가 파괴 이후 지연 추가 되도록 수정
---
---
=> [REFACTOR/VG-28] 로드된 씬 오브젝트 추가가 파괴 이후 지연실행 되도록 수정

Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp, Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h, Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
develop <- fix/VG-29/assetbrowser_bug
---
- AssetBrowser 우 클릭 안먹는 버그 수정
- 폴더 Copy못하는 부분 가시성 향상
---
=> [FIX/VG-29] AssetBrowser 우 클릭 안먹는 버그 수정

Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GizmoManager.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/Interface/IDropItem.h
develop <- feature/VG-28/gizmo_bug_fix
---
- [기즈모 컬링시 잘못된 행렬 사용하는 버그 수정](https://github.com/Scarecrow37/VanishingGround/commit/6c278fbe9412a5695e8b611db757744c059a78c7)
- 
---
---
=> [FIX/VG-28] scene gizmo bug fix

Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
develop <- fix/VG-/scene_load_resource_safe
---
- 씬 리소스 로드 안전하게 하도록 수정
---
---
=> [FIX/VG-28] 씬 리소스 로드 안전하게 하도록 수정

Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIRoot.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/Camera/CameraComponent.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/ReturnToMapNavi.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/NewGame.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/NewGame.h, Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/Option.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/PreferencesManager.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/PreferencesManager.h, Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/System/QTESystem.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/System/QTESystem.h, Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/UI/QTEUIManager.cpp, Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/UI/QTEUIManager.h, Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
develop <- fix/VG-373/main_menu_fix
---
- QTE 가이드 버튼 출력 함수 추가
- 플레이어 턴 A홀드 액션 추가 (ImGui 사용
- MainMenu의 NewGame이 Path가 아닌 Guid를 저장하도록 변경
- 카메라 컴포넌트의 WolrdToViewPort함수 제대로 동작되도록 곱셈 연산 수정
---
=> [FEATURE/VG-373] QTE 가이드 버튼 출력 및 각종 버그 픽스

Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.cpp
인스턴싱의 인덱스 값이 잘못 적용되는 버그 수정
develop <- fix/VG-438/fix/VG-438/mesh_instancing_bug
---
- 인덱스 값이 잘못 전달되는 버그 수정
---
=> [FIX/VG-438] 메쉬 인스턴싱 버그 수정

Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.cpp
`TextElement::UpdateWeight` 함수에서 주석 처리된 코드가 제거되어, `_renderer->SetFontWeight(ReflectFields->FontWeight);`가 이제 실행됩니다. 이로 인해 글꼴 두께를 설정하는 기능이 활성화되었습니다.
develop <- fix/VG-415/ui
---
- 글꼴 두께
---
---
- Git Issue: #
- Jira Ticket Number: VG-415
=> [FEATURE/VG-415] 글꼴 두께 설정 기능 활성화

Source/GA6thFinal_Framework/GraphicsEngine/SDFTextRenderer.cpp
develop <- fix/VG-449/measure_string_error
---
- MeasureString 함수에서 범위 검사 불일치 수정
- null 체크 및 빈 텍스트 처리 안전 장치 추가
- 사용되지 않는 calculatedBounds 변수 제거
- 코드 가독성 및 메모리 안전성 개선
---
---
관련된 Git Issue 번호와 Jira Ticket Number 링크
- Git Issue: #603 
- Jira Ticket Number: VG-436
=> [FIX/VG-449] SDFTextRenderer 코드 정리 및 안전성 개선
