- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/ReflectHelper.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/TProperty.hpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineLogger.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineLogger.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/LogLevel.h
- Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/TestComponent.h
- Source/GA6thFinal_Framework/ProjectVG/ProjectVG.vcxproj
- Source/GA6thFinal_Framework/ProjectVG/ProjectVG.vcxproj.filters
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorLogsTool/EditorLogsTool.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorLogsTool/EditorLogsTool.h
- Source/GA6thFinal_Framework/ProjectVG/Source/TestEditor/ReflectTestEditor.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/TestEditor/ReflectTestEditor.h
feature_scene_manager_update -> develop
- Scene Manager 메트럭스 업데이트 부분 제일 나중에 하도록 순서 변경
- DLL에서 로그 출력시 터지는 문제 수정
- 리플랙션 및 프로퍼티 매크로 정리 및 개선
- 테스트 결과 이상 없습니다.
> [FIX] DLL에서 로그 호출시 팅기는 버그 수정

- .github/workflows/bump-on-develop-merge.yml
- scripts/bump-minor.sh
- scripts/bump-patch.sh
feature/git_action_versioning -> main
---
- bump-on-develop-merge workflow 추가
- workflow에서 실행하는 bump-minor bash 추가
- workflow에서 실행하는 bump-patch bash 추가
---
.
---
- Git Issue: #
> [DOCS] Create versioning action

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorDockSpace.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorDockSpace.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorMenuBar.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorMenuBar.h
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorProjectMenu.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorProjectMenu.h
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorSceneMenu.h
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorSettingMenu.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorSettingMenu.h
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorWindowMenu.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorWindowMenu.h
feature/filesystem -> develop
---
- Editor 버그 수정 및 메모리 릭 수정
---
---
- Git Issue: #
> [FEAT] filesystem

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorMenuBar.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorDebugView.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorInspectorView.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorSceneMenu.h
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorSceneView.cpp
fix/editor -> develop
---
- 빌드 안되는 오류 수정 및 디버그용 로그 제거
---
---
- Git Issue: #
> [FIX] editor

- .github/workflows/bump-on-develop-merge.yml
feature/Scarecrow37-patch-1 -> main
---
- Git Action 변경
---
.
---
- Git Issue: #
> [DOCS] Update bump-on-develop-merge.yml

- Source/GA6thFinal_Framework/FileSystem/Core/FileObserver.cpp
- Source/GA6thFinal_Framework/FileSystem/Core/FileObserver.h
- Source/GA6thFinal_Framework/FileSystem/Core/FileSystem.cpp
- Source/GA6thFinal_Framework/FileSystem/Core/FileSystem.h
- Source/GA6thFinal_Framework/FileSystem/Extra/FileContext.cpp
- Source/GA6thFinal_Framework/FileSystem/FileHelper.h
- Source/GA6thFinal_Framework/FileSystem/Type/FileDataType.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
chore/filesystem -> develop
---
- 디버그 로그 코드 강화
- 디버그 빌드에서만 작동하며, 함수는 스레드-세이프.
---
---
- Git Issue: #
> [CHORE] 디버그 로그 코드 추가에 대한 풀 리퀘스

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorDockSpace.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorDockSpace.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorEnum.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorMenuBar.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorMenuBar.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorTool.h
- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorAssetBrowser.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorDebugView.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorHierarchyView.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorInspectorView.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorInspectorView.h
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorSceneView.cpp
chore/editor -> develop
---
- 에디터 일부 객체 네이밍 수정.
- 에디터 관련 디버그 코드 추가
- EditorTool order정렬 안되는 현상 수정
- 테스트 코드 삭제
---
---
- Git Issue: #
> [CHORE] 에디터 네이밍 수정 및 디버그 코드 추가

- .github/workflows/bump-on-develop-merge.yml
document/stop_tagging_action_if_merged_from_none -> main
---
- 병합의 From Branch가 feature 또는 fix가 아닌 경우 Action을 멈추고 종료.
---
.
---
- Git Issue: #
> [FIX] Add if when merged from none

- Source/GA6thFinal_Framework/FileSystem/Core/FileSystem.cpp
- Source/GA6thFinal_Framework/FileSystem/Type/FileDataType.h
chore/filesystem -> develop
---
- 임시 변수 참조 문제 수정
---
---
- Git Issue: #
> [CHORE] 임시 변수 참조 문제 수정

- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/DragDropTypes/DragDropTransform.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
- Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorHierarchyView.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorHierarchyView.h
- Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorLogsTool/EditorLogsTool.cpp
feature/scene_editor_dev -> develop
---
- 에디터끼리 DragDrop 가능하도록 DragDropTypes에 정의
---
---
> [FEAT] 에디터끼리 DragDrop 가능하도록 DragDropTypes에 정의

- .github/pull_request_template.md
develop <- feature/VG-134/update_pull_request_template
---
- 반영 브랜치 부분 수정
---
.
---
- Git Issue: #
- Jira Ticket Number: VG-134
> [CI/VG-134] Pull Request Template 수정

- .github/workflows/create-jira-issue.yml
main <- feature/VG-135/update_create_jira_issue_action
---
- Jira Issue 타입을 Task 고정에서 Task, SubTask로 분류
- Branch 자동 생성 삭제
- Issue 제목 자동 수정 형식 변경
---
.
---
- Git Issue: #
> [CI/VG-135] Jira 이슈 생성 Actino 수정

- .github/workflows/create-jira-issue.yml
main <- feature/VG-135/update_create_jira_issue_action
---
-  Step이 정상 동작 하지 않는 문제 해결
---
.
---
- Git Issue: #
> [CI/VG-135] Create Task 에서 If 를 안타는 문제

- .github/workflows/create-jira-issue.yml
main <- feature/VG-135/update_create_jira_issue_action
---
- Task 생성 도중 실패하는 문제 해결
---
.
---
- Git Issue: #
> [CI/VG-135] Task 생성 도중 실패하는 문제 해결

- .github/workflows/create-jira-issue.yml
---
- Issue 제목이 정상적으로 변경되지 않는 문제 해결
---
.
---
- Git Issue: #
> [CI/VG-135] Issue 제목이 정상적으로 변경되지 않는 문제 해결

- .github/workflows/create-jira-issue.yml
---
- Issue 제목 정상적으로 변경
---
.
---
- Git Issue: #
> [CI/VG-135] 여전히 제목이 정상적이지 않은 문제 해결

- .github/workflows/create-jira-issue.yml
---
- Issue 제목
---
.
---
- Git Issue: #
> [CI/VG-135] 한번만 더 해보자

- .github/workflows/create-jira-issue.yml
---
- 명령 교체
---
.
---
- Git Issue: #
> [CI/VG-135] 다시 한번 가즈아

- .github/workflows/create-jira-issue.yml
---
- gh 설치법 변경
---
.
---
- Git Issue: #
> [CI/VG-135] gh 설치법 변경

- .github/ISSUE_TEMPLATE/bug-issue-form.yml
- .github/ISSUE_TEMPLATE/feature-issue-form.yml
develop <- fix/VG-135/update_create_jira_issue_action
---
- Bug, Feature Issue Template 변경
- Branch 이름 작성 부분 삭제
- 에픽 -> 에픽(작업)으로 설명 추가
---
.
---
- Git Issue: #
> [CI/VG-135] Issue Template 변경

- .github/workflows/create-jira-issue.yml
---
- 문법 오류
---
.
---
- Git Issue: #
> [CI/VG-135] 문법 오류 제거

- .github/ISSUE_TEMPLATE/issue-form.yml
---
- template 하나 더 변경
---
.
---
- Git Issue: #
> [CI/VG-135] 이거가 정답인가?

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.h
[FEATURE] GetClientSize 함수 추가
develop <- feature/VG-155/application_client_size
---
- 클라이언트의 크기를 얻는 기능 추가
---
---
> [FEATURE] GetClientSize 함수 추가

- Source/GA6thFinal_Framework/.clang-format
main <- fix/VG-157/clang_format
---
- ColumnLimit 옵션 삭제
---
---
- Git Issue: #77
- Jira Ticket Number: [VG-157](https://gojh1124.atlassian.net/browse/VG-157)
[VG-157]: https://gojh1124.atlassian.net/browse/VG-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [STYLE/VG-157] ColumnLimit 옵션 삭제

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderPass.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderPass.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderTarget.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderTarget.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderTechnique.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderTechnique.h
develop <- feature/VG-32/feature_dx12_add
---
-renderpass 래핑
-rendertechnique 래핑
-renderscene 래핑
---
---
- Git Issue: #
> [FEATURE] dx12 렌더 프레임워크 추가.

- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/DragDropTypes/DragDropAsset.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/DragDropTypes/DragDropTransform.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/DragDropTypes/DragDropTransform.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/ScriptTest/ScriptTestEditor.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/EngineCoresModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileEventNotifier.h
- Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/TestComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/UmScriptCore.cpp
develop <- feature/VG-28/feature_name
---
- 오브젝트 직렬화 / 역직렬화 드래그 드롭으로 가능한 기능 추가
- UmPrefab 확장자 에셋 브라우저에서 추적하도록 수정
---
---
> [feature/VG-28] 드래그 드롭 오브젝트 직렬화 기능 추가, 직렬화 파일 추적 기능 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Log/EditorLogsTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/ImGuiDX12Module.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Setting/EditorSetting.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileEventNotifier.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.h
develop <- feature/VG-/editor_system
---
- 에셋 브라우저의 독립적 파일 Copy&Paste구현. 중복 파일에 대한 유니크 파일 이름 생성
- 에셋 브라우저에서 파일 Open 등의 이벤트 요청 기능 추가
---
---
- Git Issue: #
> [feature/VG-29] 에셋 브라우저 Copy&Paste 간단 구현 및 이벤트 콜백 요청 기능 구현

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.h
- Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
develop <- feature/VG-28/scene_editor_dev
---
-  define 빌드 문제 수정
- Application::IsEditor() constexpr 함수로 변경
---
---
> [FEATURE/VG-28] define 빌드 문제 수정

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
- Source/GA6thFinal_Framework/GameScripts/build_debug_editor.bat
- Source/GA6thFinal_Framework/GameScripts/build_release_editor.bat
- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.h
develop <- feature/VG-28/scene_manager_dev
---
- 스크립트 빌드 배치 파일 솔루션 구성별 추가.
- 모듈 초기화 이후 호출되는 가상함수 추가.
- 코드로 씬 테스트 가능하도록 신규 함수 추가
---
---
> [FEATURE/VG-28] 코드에서 씬 로드 및 테스트 가능하도록 기능 수정

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
develop <- feature/VG-/editor_system
---
- 에디터 인스펙터 포커싱이 마우스 뗄 때 포커싱하도록 변경
---
---
- Git Issue: #
> [FIX/VG-29] 에디터 포커싱 조작 개선

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/DragDropTypes/DragDropAsset.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
---
- 드래그 이벤트 스크립트 호환성을 위해 구조 변경
---
---
- Git Issue: #
> [fix/VG-29] 드래그 이벤트 스크립트 호환성을 위해 구조 변경

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileContext.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileObserver.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileObserver.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileDataType.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileDataType.h
develop <- feature/VG-29/file_system
---
- Guid Null문자 수정 및 Null체크 함수 추가
---
---
- Git Issue: #
> [FEATURE/VG-29] Guid Null문자 수정 및 Null체크 함수 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Device.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.cpp
---
- reference count 남는 버그 수정
- scene view 에서 focus 나가면 카메라 안 움직이게 수정
- 운용가능한 텍스쳐수 늘림.
---
---
- Git Issue: #
> [FIX/VG-32] 그래픽스 관련 버그 수정

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Command/EditorCommandTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Debug/EditorDebugTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Log/EditorLogsTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileData.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.h
- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
develop <- fix/VG-276/editor_system_bug
---
- 에디터 빌드가 아닐 때 에디터 모듈 업데이트가 실행되는 현상 수정
---
---
- Git Issue: #129
- Jira Ticket Number: VG-276
> [FIX/VG-276] 에디터 빌드가 아닐 때 에디터 모듈 업데이트가 실행되는 현상 수정

- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
---
- 플레이 메뉴 추가
---
---
- Git Issue: #
> [CHORE/VG-29] 플레이 메뉴 추가

- .github/workflows/create-jira-issue.yml
main <- Scarecrow37-patch-1
---
- Issue 생성 시 버그 하위 작업 추가
---
---
- Git Issue: #
> [CI] 버그 하위 작업 추가

- Source/GA6thFinal_Framework/Installer/Installer.vdproj
release <- feature/VG-161/installer
---
- Installer 설정 변경
---
---
- Git Issue: #
- Jira Ticket Number: VG-161
> [RELEASE] Installer 설정 변경

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Window/EditorWindowMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Window/EditorWindowMenu.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Command/EditorCommandTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Command/EditorCommandTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/DockWindow/EditorDockWindow.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/DockWindow/EditorDockWindow.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Tool/EditorTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Tool/EditorTool.h
- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
---
- 커맨드 툴에서 마우스 클릭으로 Undo, Redo하는 기능 추가
- 프레임 포커싱을 계층적으로 탐색하게 변경 (자식 프레임이 포커스중이면 부모 도킹윈도우도 포커스 처리)
- 메인 도킹 윈도우에 도킹스페이스 On/Off 메뉴 추가
---
---
- Git Issue: #
> [FEATURE/VG-29] 에디터 기능 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Tool/EditorTool.cpp
develop <- fix/VG-29/editor_esset_browser
---
- EditorTool 포커스 비정상적으로 동작하는 오류 해결
---
---
- Git Issue: #
> [FIX/VG-29] EditorTool 포커스 오류 해결

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
develop <- fix/VG-29/editor_esset_browser
---
- 테스트 코드 삭제
---
---
- Git Issue: #
> [FIX/VG-29] 테스트 코드 삭제

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/DynamicCamera/EditorDynamicCamera.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Scene/EditorSceneMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Scene/EditorSceneMenu.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/EngineCoresModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/Command/InputAutoCommand.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/InputAuto.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/TProperty.hpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/ResourceManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/ResourceManager.h
---
- Component 추가 및 삭제 Undo, Redo 추가
- 프로퍼티의 오너가 GameObject, Transform, Componet면 InputAuto 수정시 Undo, Redo 커맨드 생성하는 기능 추가
---
---
> [FEATURE/VG-28] InputAuto 커맨드 기능 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/DockWindow/EditorDockWindow.h
---
- 빌드 되도록 수정
---
---
- Git Issue: #
> [FIX/VG-29] 빌드 안되는 현상 수정

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Scene/EditorSceneMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/InputAuto.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
---
-  ImGuizmo용 ManipulateCommand 추가
- 씬 에디터 기즈모용 Undo, Redo 추가
---
---
> [FEAUTRE/VG-28] ImGuizmo용 ManipulateCommand 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Camera.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Camera.h
develop <- feature/VG-28/camera_fix_aspect
---
- Camera Aspect가 NAN 안되도록 수정
---
---
- Git Issue: #
> [FIX/VG-28] Camera fix aspect

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/FBXConverter.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/FBXConverter.h
- Source/GA6thFinal_Framework/Shaders/ps_pbr_lighting.hlsl
develop <- feature/VG-32/feature_name
---
- model editor 정보 직렬화, 역직렬화 추가 -> 모델 자체 포멧사용
- pbr에서 환경광을 임시로 albedo색상에 상수값을 곱해 사용
---
---
- Git Issue: #
> [Feature/VG-32]dx12 graphics core develop

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/DockWindow/EditorDockWindow.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/DockWindow/EditorDockWindow.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/PopupBox/EditorPopupBox.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Tool/EditorTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Tool/EditorTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.cpp
---
- 에디터 포커스 로직 개선
---
---
- Git Issue: #181
- Jira Ticket Number: VG-302
> [FIX/VG-302] 에디터 포커싱 개선

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/SkyBox.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/SkyBox.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/SkyBoxPass.cpp
develop <- feature/VG-32/dx12 _graphics_core_develop
---
- 터지는 버그수정
---
---
- Git Issue: #
> [FIX/VG-32] dx12 graphics core develop

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Play/EditorPlayMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Project/EditorBuildSettingMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Project/EditorBuildSettingMenu.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Project/EditorProjectMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Scene/EditorSceneMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Scene/EditorSceneMenu.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
- Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
develop <- feature/VG-28/game_build_system
---
- 게임 빌드 시스템 추가
---
---
> [FEATURE/VG-28] Game build system 기능 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
develop <- feature/VG-28/scene_sky_box_fix
---
- 스카이 박스 버그 수정
---
---
> [FIX/VG-28] 스카이 박스 버그 수정

- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
- Source/GA6thFinal_Framework/GameEngine/GameEngineIncludes.props
- Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
develop <- fix/VG-28/umframework_header_include_fix
---
- 빌드 문제 해결
- d3dcommon의 include 순서 문제 해결
---
---
- Git Issue: #
- Jira Ticket Number: VG-28
> [FIX/VG-28] 빌드 문제 해결

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.h
- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
develop <- feature/VG-28/wm_resize_message
---
- 클라이언트 리사이즈 하는 메시지 펌프 기능 추가.
- 에디터 모드에서 창 크기 자유롭게 설정 가능하도록 수정
---
---
- Git Issue: #
- Jira Ticket Number: VG-28
> [FEATURE/VG-28] 리사이즈 하는 메시지 펌프 기능 추가.

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Device.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Device.h
---
- 에디터 창크기 변경 추가
---
---
- Git Issue: #
> [Feature/VG-32] 에디터 창크기 변경 추가

- Source/GA6thFinal_Framework/Installer/InstallBuilder.bat
- Source/GA6thFinal_Framework/Installer/Installer.vdproj
release <- feature/VG-162/installer
---
- visual installer 옵션 변경
---
---
- Git Issue: #
- Jira Ticket Number: VG-162
> [RELEASE] v1.0.1-beta

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
develop <- fix/VG-28/scene_editor_fix
---
- 씬 에디터 커맨드 버그 수정
- 씬 메니저 ResoureceRequset에서 존재하는 GUID만 로드하도록 수정
---
---
- Git Issue: #
- Jira Ticket Number: VG-28
> [FIX/VG-28] scene editor fix

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.h
develop <- feature/VG-28/scene_editor_snap
---
- grid snap 기능 추가
- 편의성용 오브젝트 삭제 단축키 추가
---
---
> [FEATURE/VG-28] scene editor grid snap 기능 추가

- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/FocusCommand.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/HierarchyFindTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/HierarchyFindTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/ReflectHelper.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.h
- Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
develop <- feature/VG-28/game_object_tag
---
- GameObject에 tag 기능 추가
- 에디터에서 GameObject tag 변경 가능
- tag 직렬화 기능 추가
- Tag를 통한 Find 기능 추가
- Find 해볼 수 있는 FindTool 추가
---
---
> [FEATURE/VG-28] gameObject tag 기능 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.h
develop <- feature/VG-32/dx12_graphics_corer_develop
---
- Imgui용 cpu -> gpu 변환 함수 추가
---
---
- Git Issue: #212
- Jira Ticket Number: VG-307
> [FEATURE] convert cpu to gpu handle for imgui

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/BaseMesh.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/BaseMesh.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/FBXConverter.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/FBXImporter.cpp
---
- Mesh의 Vertex 정보를 가져오는 함수 추가
---
---
> [FEATURE] getter mesh vertex info

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/DynamicCamera/EditorDynamicCamera.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Play/EditorPlayMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Debug/EditorDebugTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.h
develop <- feature/VG-28/pause_system
---
- Pause 기능 추가
- Dynamic Camera 가 Unscale Delta 기준으로 이동하도록 수정
- Debug Fps 계산시 Unscale Delta 로 계산하도록 수정
- 창 최소화시 다운되는 버그 수정
---
---
> [FEATURE/VG-28] pause system 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/FBXConverter.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GraphicsBase.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GraphicsCore.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GraphicsCore.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Light.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Light.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/LightCore.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/LightCore.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.cpp
- Source/GA6thFinal_Framework/Shaders/Function.hlsli
- Source/GA6thFinal_Framework/Shaders/ps_pbr_lighting.hlsl
develop <- feature/VG-32/dx12_graphics_develop
---
- Light Lifecycle 추가
- Deferred PBR Lighting 버그 수정
---
> [REFACTOR/VG-32] Light Class Refactoring &  Deferred Lighting PBR 버그 수정

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Log/EditorLogsTool.cpp
develop <- fix/VG-28/log_bug_fix
---
- 필터 비활성화 상태로 로그 작성시 프로그램 다운되는 버그 수정
---
---
> [FIX/VG-28] 로그 버그 수정

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Window/EditorWindowMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Tool/EditorTool.h
---
- 에디터 툴 포커스 지정 기능 추가
---
---
- Git Issue: #
> [FEATURE/VG-29] 에디터 툴 포커스 지정 기능 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.cpp
develop <- feature/VG-32/feature_dx12_graphics_core_devleop
---
- 임시 post process 적용
---
> [TEST] 임시 post process

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/Component.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/Component.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
develop <- feature/VG-28/active_in_hierarchy 
---
- Active in hierarchy 맴버 변수 추가
- Active in hierarchy 값이 ActiveSelf가 변경되었을때만 계산하도록 최적화
---
---
> [FEATURE/VG-28] Active in hierarchy 최적화

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
develop <- feature/VG-28/prefab_active_bug_fix
---
- 프리팹 인스턴스화시 렌더 메시 남아있는 버그 수정
---
---
> [FIX/VG-28]  Prefab active bug fix

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/InputAuto.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/ReflectHelper.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/Base/LightComponent.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/PointLight.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/PointLight.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/SpotLight.h
develop <- feature/VG-28/input_auto_drag
---
- InputAuto 함수의 변경 UI를 DragScalar 형식으로 변경
---
---
> [FEATURE/VG-28] Input Auto 형식 drag로 변경

- Source/GA6thFinal_Framework/GameScripts/Scripts/Camera/CameraComponent.h
develop <- feature/VG-28/main_camera
---
- MainCamera 가져오는 함수 추가
---
---
> [FEATURE/VG-28] MainCamera 가져오는 함수 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/Component.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Camera/CameraComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Camera/CameraComponent.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/Base/LightComponent.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/DirectionalLight.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/DirectionalLight.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/PointLight.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/PointLight.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/SpotLight.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/SpotLight.h
develop <- feature/VG-28/scene_debug_draw
---
- Component에 에디터용 DebugDraw 가상함수 추가
- Camera Component 프러스텀 영역을 표시해주는 기능 추가
- Light Component 범위, 방향, 영역을 표시해주는 기능 추가
---
---
> [FEATURE/VG-28] Scene View용 debug draw 기능추가

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioManager/AudioManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioManager/AudioManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Callback/IncreaseGenerationCallback.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Exceptions/AudioExceptions.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/RIFF/AudioChunk.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/RIFF/AudioChunk.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Handle/AudioHandle.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Handle/AudioHandle.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Source/AudioSource.h
develop <- feature/VG-30/audio
---
- 주요 메서드 및 클래스 Summary 추가
- except / noexcept 추가
- Formatting
---
---
- Git Issue: #
- Jira Ticket Number: VG-30
> [DOCUMENT/VG-30] Audio Summary 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GraphicsCore.h
---
- Debug 모드가 아닐때도 DebugDraw 가능하게 변경
---
> [FIX/VG-32] debug 모드가 아닐때도 가능하게 변경

- Source/GA6thFinal_Framework/Installer/Installer.vdproj
develop <- patch/VG-164/editor_v121
---
- Editor v1.2.3
---
---
- Git Issue: #
- Jira Ticket Number: VG-164
> [RELEASE/VG-164] Editor v1.2.3

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GraphicsCore.cpp
---
- DebugDraw Release모드에서도 동작하게 변경
---
> [FIX] DebugDraw Release모드에서도 동작하게 변경

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
---
- filesystem module 상시 생성하게 변경 후 내부 로직을 변경
- filesystem 폴더 탐색 방식을 변경 (재귀->스택)
---
---
- Git Issue: #
> [FIX/VG-29] filesystem 터지는 버그 수정

- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
- Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Player/PlayerStats.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/FPSCounter.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/FPSCounter.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/TurnActor.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.h
- Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
develop <- feature/VG-316/turn_system
---
- Turn Mode에 Player의 무기마다 Actor를 추가하는 기능 추가
- Player Weapon 기능 추가
---
---
> [FEATURE/VG-316] turn system에 Player Weapon 추가에 따른 기능 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/SkyBox.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/SkyBox.h
develop <- fix/VG-29/model_details_fix
---
- ModelDetail import시 터짐 현상 수정
- Mode에디터 Details, View에 Camera 관련 추가
---
---
- Git Issue: #
> [FIX/VG-29] 모델 에디터 임포트 시 터지는 현상 수정

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DetachChildrenCommand.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DetachChildrenCommand.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DropPrefabCommand.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DropPrefabCommand.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/FocusCommand.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/FocusCommand.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/PackPrefabCommand.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/PackPrefabCommand.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/SetParentCommand.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/SetParentCommand.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/Command/InputAutoCommand.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/UmCommand.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Sequencer/Command/SequencerCommand.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Sequencer/Command/SequencerCommand.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Token.h
---
- Command의 Excute 성공 여부 반환 기능을 추가. 실패하면 CommandList에 등록되지 않음.
- ImGui Combo와 InputText결합한 위젯을 ImGuiHelper에 추가
---
---
> [FEATURE/VG-29] Command의 Excute 성공 여부 반환 기능을 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
develop <- fix/VG-28/ray_picker_fix
---
- ray picker 버그 수정
- vertex snap 최적화
---
---
> [FIX/VG-28] ray picker fix

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
develop <- fix/VG-335/file_system_bug
---
- FileSystem이 Project파일에 Meta파일을 생성하는 버그 수정
---
---
- Git Issue: #334
- Jira Ticket Number: VG-335
> [FIX/VG-335] FileSystem이 Project파일에 Meta파일을 생성하는 버그 수정

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
develop <- feature/VG-28/animator_resource
---
- animator resource bug fix
---
---
> [FIX/VG-28] animator resource bug fix

- Source/GA6thFinal_Framework/AudioModule/Callback.cpp
- Source/GA6thFinal_Framework/AudioModule/Callback.h
- Source/GA6thFinal_Framework/AudioModule/System.cpp
- Source/GA6thFinal_Framework/AudioModule/System.h
- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioModule.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
- Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/AudioComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/AudioComponent.h
- Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
develop <- feature/VG-164/audio_component
---
- Audio System 구조 개선
- Callback 보다 System이 먼저 해제되어서 funtional에서 이중 해제되는 부분 수정(Finalize 추가)
- Callback에 직접 매번 functional 교체에서 Handle 교체로 변경
- Audio App Module 추가
- Wav 파일 Asset Brower에 보이도록 수정
- Scene Manager의 Resource Manager의 Path 이중 확인 수정
- Audio Component 추가
---
---
- Git Issue: #
- Jira Ticket Number: VG-164
> [FEATURE/VG-164] Audio Component 추가

- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
- Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/AdditionalDamage/AdditionalDamageAction.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/TurnAction.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponElement/WeaponElement.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponElement/WeaponElement.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponSystem.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponSystem.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.h
develop <- feature/VG-317/alpha_weapon
---
- WeaponTable에 stats만 저장하는게 아니라 WeaponElement를 저장해 Aciton을 같이 저장하도록 수정
- WeaponTable 에디터 변경.
- 알파 위한 무기 5종 테이블에 추가 (액션 제외)
---
---
> [FEATURE/VG-317] alpha weapon

- Source/GA6thFinal_Framework/GameEngine/project_build_debug.bat
- Source/GA6thFinal_Framework/GameEngine/project_build_release.bat
- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/FPSCounter.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/LogOutput.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/LogOutput.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Condition/EnemyDeadCondition.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyDeadState.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Condition/PlayerDeadCondition.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerDeadState.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/GameClearState.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/RoundStartPhase.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/TurnListEmptyState.cpp
- Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
develop <- feature/VG-316/character_animation
---
- 프리 프리 알파용 캐릭터 애니메이션 연출 수정
- 빌드 버전용 로그 컴포넌트 추가
---
---
> [FEATURE/VG-316] 프리프리 알파 character animation 수정

- Source/GA6thFinal_Framework/Installer/Installer.vdproj
develop <- feature/VG-180/editor_v133
---
- 바로가기 파일 이름 변경
---
---
> [BUILD/VG-180] 인스톨러 설정 변경

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/GraphicsBase.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/GraphicsBase.h
---
-공격 빗나감 Log 추가
- Transform SetParent 이벤트 호출 안하는 버그 수정.
- 프리팹 인스턴스화 버그 수정.
---
---
> [FEATURE/VG-28] 프리팹 및 Transform 버그 수정

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
develop <- refactor/VG-28/game_object_refactor
---
- Transform 리팩토링
- 프리팹 인스턴스 갱신 버그 수정
- GameObjectFactory 리팩토링
---
---
> Refactor/vg 28/game object refactor

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/DynamicCamera/EditorDynamicCamera.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.cpp
develop <- feature/VG-28/prefab_scene_load_bug
---
- 프리팹 버그 버그 버그 수정 수정 수정
---
---
> [FIX/VG-28] prefab scene load bug

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RendererFileEvent.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RendererFileEvent.h
- Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.h
- Source/GA6thFinal_Framework/Shaders/RTShaders.hlsl
---
- 프로젝트 저장 시 `Render Property` 도 같이 저장되도록 수정
- `G-Buffer` 프로퍼티 에디터 추가
---
> [FEATURE/VG-32] Graphics Renderer Editor 기능 개선

- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
- Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/CharacterStats.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Enemy/EnemyStats.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Enemy/EnemyStatsComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Enemy/EnemyStatsComponent.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/MonsterHp/MonsterHpView.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/MonsterHp/MonsterHpView.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/TurnQueue/TurnQueueView.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Weapon/WeaponView.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/Hp/HpViewModel.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/Hp/HpViewModel.h
- Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
- Source/GA6thFinal_Framework/UserInterfaceModule/Model.h
develop <- feature/VG-180/pre_alpha_ui
---
- MVVM Model 개선
- Monster Stats HP MVVM Model로 변경
- Monster HP UI 임시 추가
---
---
- Git Issue: #
- Jira Ticket Number: VG-180
> [FEATURE/VG-180] Monster HP UI 추가

- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
- Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/BGMManager.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/BGMManager.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22010.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22011.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22012.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22013.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/EnemyActionBase.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/EnemyActionBase.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyDeadState.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.h
- Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
develop <- feature/VG-180/sound
---
- 사운드 프리 알파 버전용 삽입
---
> [FEATURE/VG-29]사운드 프리 알파 버전용 삽입

- Source/GA6thFinal_Framework/GraphicsEngine/BrightExtractPass.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/DownAndUpSamplingPass.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/Module/GaussianBlurModule.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/Module/GaussianBlurModule.h
- Source/GA6thFinal_Framework/GraphicsEngine/OutLinePass.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/ParticleRibbonPass.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/ParticleSpritePass.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/ResourceBase.h
- Source/GA6thFinal_Framework/GraphicsEngine/Structs.h
- Source/GA6thFinal_Framework/Shaders/CommonData.hlsli
- Source/GA6thFinal_Framework/Shaders/CommonDefines.hlsli
- Source/GA6thFinal_Framework/Shaders/CommonStructs.hlsli
- Source/GA6thFinal_Framework/Shaders/ps_blend.hlsl
- Source/GA6thFinal_Framework/Shaders/ps_gaussianblur_x.hlsl
- Source/GA6thFinal_Framework/Shaders/ps_gaussianblur_y.hlsl
develop <- feature/VG-309/bloom_quality_up
---
- `Bloom`의 각 샘플링 단계마다 `Gaussian Blur` 효과를 줘서 더 부드러운 `Bloom` 효과를 내도록 변경
---
> [FEATURE/VG-309] Bloom quality up

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/OpenXLSXHelper.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/OpenXLSXHelper.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelParser/ImGuiColumnSheetParser.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelParser/ImGuiColumnSheetParser.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationElement/RevelationElement.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.h
develop <- feature/VG-330/revelation_excel_pareser
---
- 계시 테이블 에디터에 엑셀 파일 파싱 기능 추가
- 플레이어 공격 선택 거꾸로 되는 버그 수정
---
---
> [FEATURE/VG-330] revelation excel pareser 기능 추가

- Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
develop <- feature/VG-330/revelation_excel_pareser
---
- 일반 빌드 컴파일 에러 문제 해결
---
---
> [FIX/VG-330] 일반 빌드 컴파일 에러 문제 해결

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Interface/IEditorObject.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
develop <- feature/VG-28/copy_component
---
- Trasnform 복사 및 붙여넣기 기능 추가
- Component 복사 및 붙여넣기 기능 추가
---
---
> [FEATURE/VG-28] copy component 및 copy trasnform 기능 추가

- Source/GA6thFinal_Framework/InstallerCusomAction/InstallerCusomAction.vcxproj
develop <- pacth/VG-180/feature_name
---
- 커스텀 액션 프로젝트 설정 변경
---
---
> [BUILD/VG-180] 커스텀 액션 프로젝트 설정 변경

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/DeferredPBRLitPass.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/GraphicsCore.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/GraphicsCore.h
- Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.h
- Source/GA6thFinal_Framework/GraphicsEngine/Renderer.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/Renderer.h
- Source/GA6thFinal_Framework/GraphicsEngine/SkyBox.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/SkyBox.h
- Source/GA6thFinal_Framework/GraphicsEngine/SkyBoxPass.cpp
- Source/GA6thFinal_Framework/Shaders/ps_ssr.hlsl
develop <- feature/VG-356/skybox_ibl
---
- skybox의 env와 ibl texture 리드 방식 변경
---
> [FEATURE/VG-356] skybox의 ibl과 env 분리

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Scene/EditorSceneMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/TProperty.hpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
develop <- fix/VG-28/scene_sky_box_tool
---
- 씬 스카이박스 설정하는 창 개선
- 스카이박스 설정 버그 수정
- 구버전 씬파일 호환 개선
---
---
> [FIX/VG-28] ENV, IBL 따로 설정하는 기능 개선

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/EngineCoresModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/InputReciver/InputReceiver.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/InputReciver/InputReceiver.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Component/TestComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Component/TestComponent.h
develop <- feature/VG-28/input_receiver
---
- inputReceiver의 Destroy 버그 수정 및 최적화
- 씬 에디터의 Guizmo 버그 수정
- 하이러키 에디터 리팩토링
---
---
> [REFACTOR/VG-28] input receiver

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/RenderPassData/EditorRenderPassData.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderPassDataHelper.h
- Source/GA6thFinal_Framework/GraphicsEngine/Graphics_Structs.h
- Source/GA6thFinal_Framework/GraphicsEngine/ShadowMapPass.cpp
develop <- fix/csm
---
- Cascade Shadow Map 기능 개선 및 버그 수정
---
> [FEATURE] Cascade Shadow Map 기능 개선 및 버그 수정

- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/Base/TurnModeStateBase.cpp
develop <- feature/VG-316/turn_mode_refactor
---
- 턴 모드 리팩터
- Player System과 Turn System 분리
---
---
> [REFACTOR/VG-316] turn mode refactor

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
develop <- feature/VG-29/file_system
---
- AssetID로 Guid 반환하는 기능 추가
---
> [FEATURE/VG-29] AssetID로 Guid 반환하는 기능 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
develop <- fix/VG-28/prefab_bug_fix
---
- 프리팹화시 UI 남아있는 버그 수정
---
---
> [FIX/VG-28] prefab bug fix

- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
- Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
- Source/GA6thFinal_Framework/GameEngine/PreferencesSystem.cpp
- Source/GA6thFinal_Framework/GameEngine/PreferencesSystem.h
- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/RenderPassData/EditorRenderPassData.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/EngineCoresModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/PreferencesSystem.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/PreferencesSystem.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderPassDataHelper.h
- Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
- Source/GA6thFinal_Framework/GraphicsEngine/FogLightInjectionPass.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/GraphicsConstroller.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/GraphicsConstroller.h
- Source/GA6thFinal_Framework/GraphicsEngine/GraphicsController.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/GraphicsController.h
- Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj
- Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj.filters
- Source/GA6thFinal_Framework/GraphicsEngine/Graphics_Structs.h
- Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.h
- Source/GA6thFinal_Framework/GraphicsEngine/RenderTechnique.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/RenderTechnique.h
- Source/GA6thFinal_Framework/GraphicsEngine/SSAOWritePass.cpp
- Source/GA6thFinal_Framework/GraphicsEngine/Structs.h
- Source/GA6thFinal_Framework/GraphicsEngine/VolumetricFogTechnique.cpp
- Source/GA6thFinal_Framework/Shaders/CommonStructs.hlsli
- Source/GA6thFinal_Framework/Shaders/cs_light_injection.hlsl
- Source/GA6thFinal_Framework/Shaders/ps_gbuffer.hlsl
develop <- feature/VG-375/preferences_system
---
- Fog Anisotropy, Light Shaft Anisotropy 분리
- preferesces system 초기작업
---
---
- Git Issue: #
- Jira Ticket Number: VG-375
> [FIX/VG-375] Fog Anisotropy, Light Shaft Anisotropy 분리 및 preferesces system 초기작업

- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Image/ImageElement.h
develop <- feature/VG-409/public_reset_to_sprite_size
---
- Image Element에 public 함수 설명 추가
- Image Element에 "ResetToSpriteSize" 함수 공개
---
---
- Git Issue: #
- Jira Ticket Number: VG-409
> [DOCUMENT/VG-409] 이미지 메서드 주석 추가 및 수정

- Source/GA6thFinal_Framework/UserInterfaceModule/Model.h
develop <- feature/VG-410/vector_model_at
---
- MVVM::Model<vector>에 인덱스 접근을 추가
---
---
- Git Issue: #
- Jira Ticket Number: VG-410
> [FEATURE/VG-410] MVVM 네임스페이스에 at 함수 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GizmoManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.cpp
develop <- feature/VG-28/ray_picker_bug_fix
---
- 씬 뷰의 ImGuizmo ID로 인한 버그 수정
---
---
> [FIX/VG-28] scene view guizmo bug fix

- Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Project/EditorProjectMenu.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/LogLevel.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/AnimationComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelDataSystem/ExcelDataSystem.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/SceneTransition/SceneTransitionComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/RoundOnceCondition/RoundOnceCondition.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/DrawUIComponent/DrawUIComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Utility/SingletonHelper.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponSystem.cpp
develop <- feature/VG-28/is_play_bug_fix
---
- Global::IsPlay 함수 제거
- UmCore->IsPlay 함수 추가
- IsPlay가 잘못된 값 반환하는 버그 수정
---
---
> [FIX/VG-28] is play bug fix

- Source/GA6thFinal_Framework/GameScripts/Scripts/AccessorySystem/AccessorySystem.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/AccessorySystem/AccessorySystem.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelDataSystem/ExcelDataSystem.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelDataSystem/ExcelDataSystem.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.h
develop <- feature/VG-316/excel_table_system
---
- 데이터 테이블 접근시 u8string_view 사용하도록 수정
- Weapon, Accessory, Revelation 테이블들이 엑셀 테이블 시스템 사용하도록 리팩토링
---
---
> [FEATURE/VG-316] excel table system

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UINavigationComponent.cpp
`isSelected` 변수를 `false`로 설정하여 사용자가 버튼을 눌렀을 때 선택 상태를 해제하는 기능을 추가했습니다.
develop <- fix/VG-415/ui_navigation
---
- Navigation Route 추가시 키 입력후 선택 해제
---
---
- Git Issue: #
- Jira Ticket Number: VG-415
> [FIX/VG-415] 선택 상태 해제 기능 추가

- Source/GA6thFinal_Framework/GraphicsEngine/ParticleManager.cpp
develop <- feature/VG-332/ribbon_renderer
---
- scene view에서 이펙트 출력 안되는 버그 해결
---
---
- Git Issue: #
- Jira Ticket Number: VG-332
> Scene View 에서 이펙트 안보이는 버그 픽스

- Source/GA6thFinal_Framework/AudioModule/System.cpp
- Source/GA6thFinal_Framework/AudioModule/System.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Manager/AudioManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Manager/AudioManager.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
develop <- fix/VG-424/audio
---
- 오디오 재생 후 빌드 스크립트 시 프로그램이 충돌과 함께 꺼지는 현상 수정
---
---
- Git Issue: #
- Jira Ticket Number: VG-424
> [FIX/VG-424] Audio 버그 수정

- Source/GA6thFinal_Framework/AudioModule/System.cpp
- Source/GA6thFinal_Framework/AudioModule/System.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Manager/AudioManager.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Manager/AudioManager.h
develop <- feature/VG-390/audio
---
- 루프 재생 기능 추가
---
---
- Git Issue: #
- Jira Ticket Number: VG-421
> [FEATURE/VG-421] 루프 재생 기능 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Sequencer/EditorTimelineTrackSequencer.h
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
- Source/GA6thFinal_Framework/GameEngine/Source/Engine/TimelineCore/Track/TimelineEventTrack.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/Editor/QTEEditor.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/Editor/QTEEditor.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/System/QTESystem.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/System/QTESystem.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/Track/QTETrack.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/Track/QTETrack.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
develop <- feature/VG-373/qte_system
---
- QTE 에디터 개선
- 무기 애니메이션 딜레이 적용 안되던 버그 수정
---
> [CHORE/VG-373] 무기 애니메이션 딜레이 적용되도록 변경, 에디터 개선

- Source/GA6thFinal_Framework/GraphicsEngine/Enums.h
develop <- feature/VG-432/fix_ssao
---
- 어떤 작업을 했는지 요약
- 주요 변경 사항 bullet point로 작성
---
---
- Git Issue: #
- Jira Ticket Number: VG-432
> [FIX/VG-432] ui data max 갯수 256->512

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/PreferencesSystem.cpp
- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
- Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/SoundButton.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Audio/TestAudioComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Audio/TestAudioComponent.h
develop <- feature/VG-375/preferences_system
---
- 오디오 음량 조절 추가
- 음량조절을 위한 오디오 테스트 컴포넌트 추가
---
---
- Git Issue: #
- Jira Ticket Number: VG-375
> [FEATURE/VG-375] audio 음량조절 추가

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIRoot.cpp
develop <- fix/VG-415/ui
---
- UIRoot.cpp: View Order 재정렬 버튼 추가
---
---
- Git Issue:
- Jira Ticket Number: VG-415
> [FIX/VG-415] UI 시스템 수정 및 UIRoot 컴포넌트 개선

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/GraphicsModule.cpp
- Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
- Source/GA6thFinal_Framework/GameScripts/Scripts/Map/Stage.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Map/Stage.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/ImportGraphicsSetting.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/ImportGraphicsSetting.h
develop <- feature/VG-372/map_system
---
- Stage마다 각 라이트 세팅을 적용할 수 있도록 기능 추가
- LightSetting을 불러올 수 있는 컴포넌트 추가
---
> [FEATURE/VG-372] 라이트 세팅을 불러올 수 있는 컴포넌트 추가

- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.cpp
develop <- fix/VG-415/ui
---
- 텍스트 사이즈 버그 수정
---
---
- Git Issue: #
- Jira Ticket Number: VG-415
> [FIX/VG-415] 텍스트 사이즈 버그 수정

- Source/GA6thFinal_Framework/GameScripts/Scripts/CombatUIManager/CombatUIManager.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/CombatUIManager/CombatUIManager.h
develop <- feature/VG-444/combat_ui
---
- CombatUIManager 댕글링포인터 접근 수정
---
> [FIX/VG-444] CombatUIManager 댕글링포인터 접근 수정

- Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Light/Base/LightComponent.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Map/RewardPopup.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/Map/RewardPopup.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/RoundOnceCondition/RoundOnceCondition.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/RoundOnceCondition/RoundOnceCondition.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Map/StageFocusView.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Map/StageFocusView.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/RevelationsView/RevelationsView.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/RevelationsView/RevelationsView.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/TurnQueue/TurnQueueView.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/TurnQueue/TurnQueueView.h
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Weapon/WeaponView.cpp
- Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Weapon/WeaponView.h
- Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
develop <- fix/VG-28/heap_corruption
---
- 댕글링 의심가는 코드들 수정
---
---
> [FIX/VG-28] round once action 버그 수정
